<?php
/*
 * Copyright (c) 2014, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

////////////////////////////////////////////////////////////////////////////////
// create fresh form

$form = new sly_Form($_router->getUrl(null, 'export'), 'POST', t('im_export_export'), '', 'export');

$form->getSubmitButton()->setValue(t('im_export_db_export'));
$form->setResetButton(null);

////////////////////////////////////////////////////////////////////////////////
// main options

$dump    = new sly_Form_Input_Checkbox('dump', t('im_export_dump'), 1, t('im_export_include_dump'), null, true);
$comment = new sly_Form_Input_Text('comment', t('im_export_comment'), '');
$dirs    = new sly_Form_Select_Checkbox('directories', t('im_export_additional_folders'), null, $dirs);

$form->addElements(array($dump, $comment, $dirs));

////////////////////////////////////////////////////////////////////////////////
// dump options

$users        = new sly_Form_Input_Checkbox('users', t('im_export_include_users'), 1, t('im_export_include_users_help'), null, true);
$diffFriendly = new sly_Form_Input_Checkbox('diff_friendly', t('im_export_diff_friendly'), 1, t('im_export_diff_friendly_help'));

$users->setHelpText(t('im_export_include_users_helptext'));

$form->beginFieldset('Datenbank-Export-Optionen');
$form->addElements(array($canAccessUsers ? $users : null, $diffFriendly));

////////////////////////////////////////////////////////////////////////////////
// store or download?

$download = new sly_Form_Select_Radio('download', 'Download', array(0), array(
	0 => t('im_export_save_on_server'),
	1 => t('im_export_download_as_file')
));

$filename = new sly_Form_Input_Text('filename', t('im_export_filename'), isset($filename) ? $filename : 'sly_'.date('Ymd'));
$filename->setHelpText(t('im_export_hint_filename'));

$form->beginFieldset('Downloadoptionen');
$form->addElements($canDownload ? array($download, $filename) : array($filename));

////////////////////////////////////////////////////////////////////////////////
// and print it

?>
<div class="sly-content">
	<?php
	// print messages
	print sly_Helper_Message::renderFlashMessage();

	// print text and form
	print '<p>'.t('im_export_intro_export').'</p>';
	print $form->render();
	?>
</div>
