<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$layout = sly_Core::getLayout();
$layout->addCSSFile('../data/dyn/public/import_export/css/backend.css');
$layout->pageHeader(t('im_export_importexport'), $subpages);
