<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$is06  = sly_Core::getVersion('X.Y') === '0.6';
$base  = $is06 ? '../data/dyn/public/import_export/' : sly_Util_AddOn::assetBaseUri('sallycms/import-export');
$user  = sly_Util_User::getCurrentUser();
$canEx = $user->isAdmin() || $user->hasRight('import_export', 'export');
$canIm = $user->isAdmin() || $user->hasRight('import_export', 'import');
$canDL = $user->isAdmin() || $user->hasRight('import_export', 'download');

// prepare table
$table = new sly_Table('exports');
$table->addColumn(new sly_Table_Column('<img src="'.$base.'images/backup.png" alt="" />', '', '', array('class' => 'sly-col-icon sly-icon')));
$table->addColumn(new sly_Table_Column('Datei', '', '', array('class' => 'sly-col-file')));

if ($canIm || $canEx) {
	$table->addColumn(new sly_Table_Column('Optionen', '', '', array('class' => 'sly-col-funcs')));
}

$table->addColumn(new sly_Table_Column('Datum', '', '', array('class' => 'sly-col-date')));
$table->addColumn(new sly_Table_Column('Größe', '', '', array('class' => 'sly-col-size')));
$table->setIsEmpty(empty($files));
$table->setEmptyNotice(t('im_export_no_backups_available'));

?>
<div class="sly-content">
	<?
	// print messages
	if (!empty($info))    print sly_Helper_Message::info($info);
	if (!empty($warning)) print sly_Helper_Message::warn($warning);

	// intro text
	print '<p>'.t('im_export_intro_import').'</p>';

	// print table
	$table->openBuffer();

	foreach ($files as $file) {
		$filename = $this->baseDir.$file;
		if (!file_exists($filename)) continue;

		$info    = sly_A1_Util::getArchiveInfo($filename);
		$baseURL = 'index.php?page=a1imex_import&amp;file='.urlencode($file).'&amp;func=';

		?>
		<tr>
			<td class="sly-col-icon sly-icon"><img src="<?php print $base ?>images/backup.png" alt="" /></td>
			<td class="sly-col-file">
				<?php if ($canDL): ?>
				<a href="<?= $baseURL ?>download" title="<?= sly_html($info['comment']) ?>"><?= sly_html($info['name']) ?></a>
				<?php else: ?>
				<span title="<?= sly_html($info['comment']) ?>"><?= sly_html($info['name']) ?></span>
				<?php endif ?>

				<?php if (!empty($info['description'])): ?>
				<span class="desc">(<?= sly_html($info['description']) ?>)</span>
				<?php endif ?>
			</td>

			<?php if ($canIm || $canEx): ?>
			<td class="sly-col-funcs">
				<?php if ($canIm && !empty($info['missing'])): ?>
				<span class="sly-strike import" title="<?php print t('requires').' '.sly_Util_String::humanImplode($info['missing']) ?>"><?= t('im_export_import_file') ?></span>
				<?php elseif ($canIm && !empty($info['missing']) || !$info['compatible']): ?>
				<span class="sly-strike import" title="<?php print t(($is06 ? 'component' : 'addon').'_incompatible_with_this_version') ?>"><?= t('im_export_import_file') ?></span>
				<?php elseif ($canIm): ?>
				<a href="<?= $baseURL ?>import" class="import"><?= t('im_export_import_file') ?></a>
				<?php endif ?>

				<?php if ($canEx): ?>
				<a href="<?= $baseURL ?>delete" class="delete sly-delete"><?= t('im_export_delete_file') ?></a>
				<?php endif ?>
			</td>
			<?php endif ?>

			<td class="sly-col-date"><?= sly_Util_String::formatDatetime($info['date']) ?></td>
			<td class="sly-col-size"><?= sly_Util_String::formatFilesize(filesize($filename)) ?></td>
		</tr>
		<?
	}

	$table->closeBuffer();
	print $table->render();

	?>
</div>
