<?
/*
 * Copyright (C) 2009 REDAXO
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2 as published by the
 * Free Software Foundation.
 */

/**
 * @package redaxo4
 */
?>
<div class="sly-content">
	<?

	// Meldungen ausgeben

	if (!empty($info))    print rex_info($info);
	if (!empty($warning)) print rex_warning($warning);

	// Intro-Text

	print '<p>'.$I18N->msg('im_export_intro_export').'</p>';

	// Formular erzeugen

	$form = new sly_Form('index.php', 'POST', $I18N->msg('im_export_export'), '', 'export');
	$form->setEncType('multipart/form-data');
	$form->addHiddenValue('page', 'import_export');
	$form->addHiddenValue('function', 'export');

	$options = array(
		'sql'   => $I18N->msg('im_export_database_export'),
		'configuration' => $I18N->msg('im_export_configuration_export')
	);

	$contents = new sly_Form_Select_Checkbox('types', 'Export-Typ', $types, $options);
	$filename = new sly_Form_Input_Text('filename', $I18N->msg('im_export_filename'), $filename);
	$filename->setHelpText(t('im_export_hint_filename'));

	// Verzeichnis-Auswahl erzeugen

	$root         = SLY_INCLUDE_PATH.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;
	$dirs = array(
		realpath($root.'assets')  => t('im_export_explain_assets'),
		realpath($root.'develop') => t('im_export_explain_develop'),
		SLY_MEDIAFOLDER           => t('im_export_explain_mediapool')
	);

	$root   = new sly_Form_Select_Checkbox('directories', t('im_export_additional_folders'), array(), $dirs);
	$format = new sly_Form_Select_Radio('download', 'Download', array(), array(
		0 => $I18N->msg('im_export_save_on_server'),
		1 => $I18N->msg('im_export_download_as_file')
	));

	// Formular fertigstellen und ausgeben

	$form->addElements(array($contents, $root));
	$form->beginFieldset('Downloadoptionen');
	$form->addElements(array($format, $filename));
	$form->getSubmitButton()->setAttribute('value', $I18N->msg('im_export_db_export'));
	$form->setResetButton(null);
	$form->render();

	?>
</div>